apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/appd/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: app-config
