apiVersion: v1
kind: Service
metadata:
  name: example-app
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: example-app
  type: {{ .Values.service.type }}
